apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: creadorusuarios
  template:
    metadata:
      labels:
        app: creadorusuarios
    spec:
      containers:
      - name: creadorusuarios
        image: coderhouse50045/creadorusuarios:latest  
        ports:
        - containerPort: 8080
        env:   
        - name: MONGO_URL
          value: "mongodb+srv://swtocaimaza:coderhouse@cluster0.pmzgicx.mongodb.net/jwt?retryWrites=true&w=majority&appName=Cluster0"
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: creadorusuarios
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
